language: node_js
node_js:
  - "8"
branches:
  only:
    - master
before_install:
  - echo "@fortawesome:registry https://npm.fontawesome.com/ //registry.npmjs.org/:_authToken=\${FONT_AWESOME_TOKEN}" > .npmrc
before_script:
  - node version
  - npm version
  - npm install
script:
  - npm run ghpages
