name: Build and publish package
# TODO: would it make sense to include merge to master in this event
# on:
#   push:
#     branches:
#       - testing-github-actions
on:
  release:
    types: [published]

# Only trigger, when the build workflow succeeded
# on:
#   workflow_run:
#     workflows: ["Release"]
#     types:
#       - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ssh-key: "${{secrets.ACTIONS_PUBLISH_KEY}}"
      - uses: actions/setup-node@v3
      - uses: ./.github/actions/npm-install
        with:
          token: ${{secrets.FONTAWESOME_NPM_AUTH_TOKEN}}
      - name: Build package
        run: npm run package:build
      - name: Copy package.json
        run: node scripts/copy-package-file.js
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-package
          path: distribution
  release:
    needs: build
    runs-on: ubuntu-latest
    steps: 
      - name: Download artifact
        uses: actions/download-artifact@master
        with:
          name: my-package
          path: distribution
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Publish
        run: npm publish distribution/
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}