name: Release
on:
  push:
    branches:
      - main
      - master
      - testing-github-actions
jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Release
        uses: justincy/github-action-npm-release@2.0.2
        with:
          token: ${{secrets.ACTIONS_PUBLISH_KEY}}
        id: release
      - name: Print release output
        if: ${{ steps.release.outputs.released == 'true' }}
        run: echo Release ID ${{ steps.release.outputs.release_id }}