name: Run tests
run-name: ${{github.actor}} is running pre-release tests
on:
  pull_request:
    branches:
      - master
      - main
jobs:
  npm-install:
    uses: ./.github/workflows/install-npm.yml
  tests:
    runs-on: ubuntu-latest
    needs: npm-install
    steps:
      - uses: actions/checkout@v3
      - name: Running the tests
        run: npm run test-single-run