name: Run tests
run-name: ${{github.actor}} is running pre-release tests
on:
  pull_request:
    branches:
      - master
      - main
jobs:
  npm-install:
    uses: ./.github/workflows/npm-install.yml
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Running the tests
        run: npm run test-single-run